services:
  automatest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automatest-runner
    environment:
      - TZ=America/Sao_Paulo
      - AUTOMATEST_MODE=ALL            # garante execução "TUDO" se rodar manual sem --all
    volumes:
      - ./:/app                        # monta o repo inteiro (inclui .git p/ git pull)
      - ./.env:/app/.env:ro            # SMTP + POSTMAN_API_KEY
    restart: unless-stopped
