version: "3.9"

services:
  automatest-runner:
    container_name: automatest-runner
    build:
      context: .
      dockerfile: Dockerfile
    image: automatest-runner:latest
    restart: unless-stopped

    volumes:
      - ./:/app
      - ./.env:/app/.env:ro

    environment:
      - TZ=America/Sao_Paulo

    ports: []

    healthcheck:
      test: >
        bash -lc '
        command -v postman >/dev/null 2>&1 &&
        command -v python >/dev/null 2>&1 &&
        [ -f /etc/cron.d/automatest ] &&
        pgrep -x cron >/dev/null
        '
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
